package mods.defeatedcrow.client.model.model;

import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

public class ModelCLamp {
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart ear1;
    private final ModelPart ear2;
    private final ModelPart wing1;
    private final ModelPart wing2;
    private final ModelPart tail1;
    private final ModelPart tail2;
    private final ModelPart core1;
    private final ModelPart core2;
    private final ModelPart sphere;
    private final ModelPart sphere2;
    private final ModelPart arm1;
    private final ModelPart arm2;
    private final ModelPart arm3;
    private final ModelPart blade1;
    private final ModelPart blade2;
    private final ModelPart blade3;
    private final ModelPart blade21;
    private final ModelPart blade22;
    private final ModelPart blade23;
    private final ModelPart side1;
    private final ModelPart side2;
    private final ModelPart side3;
    private final ModelPart side4;
    private final ModelPart inner1;
    private final ModelPart inner2;
    private final ModelPart barB1;
    private final ModelPart barB2;
    private final ModelPart barB3;
    private final ModelPart barB4;
    private final ModelPart barB5;
    private final ModelPart barB6;
    private final ModelPart barF1;
    private final ModelPart barF2;
    private final ModelPart barF3;
    private final ModelPart barF4;
    private final ModelPart barF5;
    private final ModelPart barF6;
    private final ModelPart barR1;
    private final ModelPart barR2;
    private final ModelPart barR3;
    private final ModelPart barR4;
    private final ModelPart barL1;
    private final ModelPart barL2;
    private final ModelPart barL3;
    private final ModelPart barL4;
    private final ModelPart head1;
    private final ModelPart head2;
    private final ModelPart head3;
    private final ModelPart head4;
    private final ModelPart cover1;
    private final ModelPart head6;
    private final ModelPart head7;
    private final ModelPart head8;
    private final ModelPart head9;
    private final ModelPart cover2;
    private final ModelPart glow1;
    private final ModelPart glow2;
    private final ModelPart top;
    private final ModelPart lod1a;
    private final ModelPart lod1b;
    private final ModelPart lod1c;
    private final ModelPart lod2a;
    private final ModelPart lod2b;
    private final ModelPart lod2c;
    private final ModelPart lod3a;
    private final ModelPart lod3b;
    private final ModelPart lod3c;
    private final ModelPart lod4a;
    private final ModelPart lod4b;
    private final ModelPart lod4c;
    private final ModelPart wingb1;
    private final ModelPart wingb2;

    public ModelCLamp(ModelPart root) {
        this.body = root.getChild("body");
        this.head = root.getChild("head");
        this.ear1 = root.getChild("ear1");
        this.ear2 = root.getChild("ear2");
        this.wing1 = root.getChild("wing1");
        this.wing2 = root.getChild("wing2");
        this.tail1 = root.getChild("tail1");
        this.tail2 = root.getChild("tail2");
        this.core1 = root.getChild("core1");
        this.core2 = root.getChild("core2");
        this.sphere = root.getChild("sphere");
        this.sphere2 = root.getChild("sphere2");
        this.arm1 = root.getChild("arm1");
        this.arm2 = root.getChild("arm2");
        this.arm3 = root.getChild("arm3");
        this.blade1 = root.getChild("blade1");
        this.blade2 = root.getChild("blade2");
        this.blade3 = root.getChild("blade3");
        this.blade21 = root.getChild("blade21");
        this.blade22 = root.getChild("blade22");
        this.blade23 = root.getChild("blade23");
        this.side1 = root.getChild("side1");
        this.side2 = root.getChild("side2");
        this.side3 = root.getChild("side3");
        this.side4 = root.getChild("side4");
        this.inner1 = root.getChild("inner1");
        this.inner2 = root.getChild("inner2");
        this.barB1 = root.getChild("barB1");
        this.barB2 = root.getChild("barB2");
        this.barB3 = root.getChild("barB3");
        this.barB4 = root.getChild("barB4");
        this.barB5 = root.getChild("barB5");
        this.barB6 = root.getChild("barB6");
        this.barF1 = root.getChild("barF1");
        this.barF2 = root.getChild("barF2");
        this.barF3 = root.getChild("barF3");
        this.barF4 = root.getChild("barF4");
        this.barF5 = root.getChild("barF5");
        this.barF6 = root.getChild("barF6");
        this.barR1 = root.getChild("barR1");
        this.barR2 = root.getChild("barR2");
        this.barR3 = root.getChild("barR3");
        this.barR4 = root.getChild("barR4");
        this.barL1 = root.getChild("barL1");
        this.barL2 = root.getChild("barL2");
        this.barL3 = root.getChild("barL3");
        this.barL4 = root.getChild("barL4");
        this.head1 = root.getChild("head1");
        this.head2 = root.getChild("head2");
        this.head3 = root.getChild("head3");
        this.head4 = root.getChild("head4");
        this.cover1 = root.getChild("cover1");
        this.head6 = root.getChild("head6");
        this.head7 = root.getChild("head7");
        this.head8 = root.getChild("head8");
        this.head9 = root.getChild("head9");
        this.cover2 = root.getChild("cover2");
        this.glow1 = root.getChild("glow1");
        this.glow2 = root.getChild("glow2");
        this.top = root.getChild("top");
        this.lod1a = root.getChild("lod1a");
        this.lod1b = root.getChild("lod1b");
        this.lod1c = root.getChild("lod1c");
        this.lod2a = root.getChild("lod2a");
        this.lod2b = root.getChild("lod2b");
        this.lod2c = root.getChild("lod2c");
        this.lod3a = root.getChild("lod3a");
        this.lod3b = root.getChild("lod3b");
        this.lod3c = root.getChild("lod3c");
        this.lod4a = root.getChild("lod4a");
        this.lod4b = root.getChild("lod4b");
        this.lod4c = root.getChild("lod4c");
        this.wingb1 = root.getChild("wingb1");
        this.wingb2 = root.getChild("wingb2");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.5F, -3F, -2F, 5, 6, 5), PartPose.offset(0F, 14F, 0F));
        root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, -2F, -1.5F, 4, 3, 4), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("ear1", CubeListBuilder.create().texOffs(0, 0).addBox(-1F, 0F, 0.5F, 1, 1, 1), PartPose.offset(0F, 8.3F, 0F));
        root.addOrReplaceChild("ear2", CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0.5F, 1, 1, 1), PartPose.offset(0F, 8.3F, 0F));
        root.addOrReplaceChild("wing1", CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, 2.5F, 1, 3, 6), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("wing2", CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, 2.5F, 1, 3, 6), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -1.5F, 4, 2, 4), PartPose.offset(0F, 17F, 0F));
        root.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, 0F, -1F, 3, 2, 2), PartPose.offset(0F, 19F, 0F));
        root.addOrReplaceChild("core1", CubeListBuilder.create().texOffs(0, 17).addBox(-1F, -1F, -1F, 2, 2, 2), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, -0.7853982F));
        root.addOrReplaceChild("core2", CubeListBuilder.create().texOffs(0, 12).addBox(-1.5F, -0.5F, -1F, 3, 2, 2), PartPose.offset(0F, 9F, 0F));
        root.addOrReplaceChild("sphere", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 6, 6, 6), PartPose.offset(0F, 14F, 0F));
        root.addOrReplaceChild("sphere2", CubeListBuilder.create().texOffs(24, 0).addBox(-2F, -2F, -2F, 4, 4, 4), PartPose.offset(0F, 14F, 0F));
        root.addOrReplaceChild("arm1", CubeListBuilder.create().texOffs(0, 13).addBox(-5F, -1F, -1F, 2, 2, 2), PartPose.offsetAndRotation(0F, 13F, -0.5F, 0F, 0.6981317F, 0.2617994F));
        root.addOrReplaceChild("arm2", CubeListBuilder.create().texOffs(0, 13).addBox(3F, -1F, -1F, 2, 2, 2), PartPose.offsetAndRotation(0F, 13F, -0.5F, 0F, -0.6981317F, -0.2617994F));
        root.addOrReplaceChild("arm3", CubeListBuilder.create().texOffs(0, 13).addBox(-1F, -1F, -4F, 2, 2, 2), PartPose.offsetAndRotation(0F, 12.5F, 0F, -0.2617994F, 0F, 0F));
        root.addOrReplaceChild("blade1", CubeListBuilder.create().texOffs(0, 17).addBox(-0.5F, 0F, -4.5F, 1, 10, 2), PartPose.offsetAndRotation(0F, 11F, 0F, -0.3490659F, 0F, 0F));
        root.addOrReplaceChild("blade2", CubeListBuilder.create().texOffs(0, 17).addBox(-0.5F, 0F, -5.5F, 1, 10, 2), PartPose.offsetAndRotation(0F, 11.5F, -0.2F, -0.3490659F, 2.234021F, 0F));
        root.addOrReplaceChild("blade3", CubeListBuilder.create().texOffs(0, 17).addBox(-0.5F, 0F, -5.5F, 1, 10, 2), PartPose.offsetAndRotation(0F, 11.5F, -0.2F, -0.3490659F, -2.234021F, 0F));
        root.addOrReplaceChild("blade21", CubeListBuilder.create().texOffs(14, 13).addBox(-0.5F, 0F, -8.7F, 1, 1, 3), PartPose.offsetAndRotation(0F, 23F, 0F, -0.5410521F, 0F, 0F));
        root.addOrReplaceChild("blade22", CubeListBuilder.create().texOffs(14, 13).addBox(-0.5F, 0F, -9.5F, 1, 1, 3), PartPose.offsetAndRotation(0F, 23.5F, -0.2F, -0.5410521F, 2.234021F, 0F));
        root.addOrReplaceChild("blade23", CubeListBuilder.create().texOffs(14, 13).addBox(-0.5F, 0F, -9.5F, 1, 1, 3), PartPose.offsetAndRotation(0F, 23.5F, -0.2F, -0.5410521F, -2.234021F, 0F));
        root.addOrReplaceChild("side1", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, -2F, -6F, 2, 14, 2), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("side2", CubeListBuilder.create().texOffs(0, 0).addBox(4F, -2F, -6F, 2, 14, 2), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("side3", CubeListBuilder.create().texOffs(0, 0).addBox(-6F, -2F, 4F, 2, 14, 2), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("side4", CubeListBuilder.create().texOffs(0, 0).addBox(4F, -2F, 4F, 2, 14, 2), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("inner1", CubeListBuilder.create().texOffs(32, 0).addBox(-4F, -2F, -4F, 8, 14, 8), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("inner2", CubeListBuilder.create().texOffs(32, 0).addBox(-3.5F, 0F, -3.5F, 7, 13, 7), PartPose.offset(0F, 8.5F, 0F));
        root.addOrReplaceChild("barB1", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, -1F, 1, 6, 1), PartPose.offsetAndRotation(0F, 8F, 0F, 1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barB2", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, 0F, 1, 6, 1), PartPose.offsetAndRotation(0F, 8F, 0F, -1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barB3", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, 8F, 1, 10, 1), PartPose.offsetAndRotation(0F, 5F, 0F, -1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barB4", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, -9F, 1, 10, 1), PartPose.offsetAndRotation(0F, 5F, 0F, 1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barB5", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, 9F, 1, 6, 1), PartPose.offsetAndRotation(0F, 10F, 0F, -1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barB6", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, -10F, 1, 6, 1), PartPose.offsetAndRotation(0F, 10F, 0F, 1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barF1", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, 0F, 1, 6, 1), PartPose.offsetAndRotation(0F, 8F, 0F, -1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barF2", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, -1F, 1, 6, 1), PartPose.offsetAndRotation(0F, 8F, 0F, 1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barF3", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, -9F, 1, 10, 1), PartPose.offsetAndRotation(0F, 5F, 0F, 1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barF4", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, 8F, 1, 10, 1), PartPose.offsetAndRotation(0F, 5F, 0F, -1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barF5", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, -9F, 1, 5, 1), PartPose.offsetAndRotation(0F, 11F, 0F, 1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barF6", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, 9F, 1, 6, 1), PartPose.offsetAndRotation(0F, 10F, 0F, -1.047198F, 1.570796F, 0F));
        root.addOrReplaceChild("barR1", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, 8F, 1, 10, 1), PartPose.offsetAndRotation(0F, 2F, 0F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild("barR2", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, -9F, 1, 10, 1), PartPose.offsetAndRotation(0F, 2F, 0F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild("barR3", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, 8F, 1, 10, 1), PartPose.offsetAndRotation(0F, 8F, 0F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild("barR4", CubeListBuilder.create().texOffs(0, 0).addBox(-5F, 0F, -9F, 1, 10, 1), PartPose.offsetAndRotation(0F, 8F, 0F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild("barL1", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, -9F, 1, 10, 1), PartPose.offsetAndRotation(0F, 2F, 0F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild("barL2", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, 8F, 1, 10, 1), PartPose.offsetAndRotation(0F, 2F, 0F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild("barL3", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, -9F, 1, 10, 1), PartPose.offsetAndRotation(0F, 8F, 0F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild("barL4", CubeListBuilder.create().texOffs(0, 0).addBox(4F, 0F, 8F, 1, 10, 1), PartPose.offsetAndRotation(0F, 8F, 0F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild("head1", CubeListBuilder.create().texOffs(0, 3).addBox(-1F, 0F, 2F, 2, 1, 2), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, 1.570796F, 0F));
        root.addOrReplaceChild("head2", CubeListBuilder.create().texOffs(0, 3).addBox(-2F, 0F, 4F, 4, 1, 1), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, 1.570796F, 0F));
        root.addOrReplaceChild("head3", CubeListBuilder.create().texOffs(0, 3).addBox(-3F, 0F, 5F, 6, 1, 1), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, 1.570796F, 0F));
        root.addOrReplaceChild("head4", CubeListBuilder.create().texOffs(0, 3).addBox(-4F, 0F, 6F, 8, 1, 1), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, 1.570796F, 0F));
        root.addOrReplaceChild("cover1", CubeListBuilder.create().texOffs(0, 3).addBox(5F, 0F, -4F, 1, 10, 8), PartPose.offset(0F, 14.5F, 0F));
        root.addOrReplaceChild("head6", CubeListBuilder.create().texOffs(0, 3).addBox(-1F, 0F, 2F, 2, 1, 2), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, -1.570796F, 0F));
        root.addOrReplaceChild("head7", CubeListBuilder.create().texOffs(0, 3).addBox(-2F, 0F, 4F, 4, 1, 1), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, -1.570796F, 0F));
        root.addOrReplaceChild("head8", CubeListBuilder.create().texOffs(0, 3).addBox(-3F, 0F, 5F, 6, 1, 1), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, -1.570796F, 0F));
        root.addOrReplaceChild("head9", CubeListBuilder.create().texOffs(0, 3).addBox(-4F, 0F, 6F, 8, 1, 1), PartPose.offsetAndRotation(0F, 11F, 0F, -0.5235988F, -1.570796F, 0F));
        root.addOrReplaceChild("cover2", CubeListBuilder.create().texOffs(0, 3).addBox(-6F, 0F, -4F, 1, 10, 8), PartPose.offset(0F, 14.5F, 0F));
        root.addOrReplaceChild("glow1", CubeListBuilder.create().texOffs(24, 0).addBox(-2F, 0F, -2F, 4, 4, 4), PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild("glow2", CubeListBuilder.create().texOffs(24, 8).addBox(-3F, 0F, -3F, 6, 6, 6), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild("top", CubeListBuilder.create().texOffs(0, 3).addBox(-1F, 0F, -1F, 2, 2, 2), PartPose.offsetAndRotation(0F, 13F, 0F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild("lod1a", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, 0F, 6F, 6, 1, 1), PartPose.offset(0F, 17F, 0F));
        root.addOrReplaceChild("lod1b", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, 6F, 4, 1, 1), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild("lod1c", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, 6F, 4, 1, 1), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild("lod2a", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, 0F, 6F, 6, 1, 1), PartPose.offset(0F, 21F, 0F));
        root.addOrReplaceChild("lod2b", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, 6F, 4, 1, 1), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild("lod2c", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, 6F, 4, 1, 1), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild("lod3a", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, 0F, -7F, 6, 1, 1), PartPose.offset(0F, 17F, 0F));
        root.addOrReplaceChild("lod3b", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -7F, 4, 1, 1), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild("lod3c", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -7F, 4, 1, 1), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild("lod4a", CubeListBuilder.create().texOffs(0, 0).addBox(-3F, 0F, -7F, 6, 1, 1), PartPose.offset(0F, 21F, 0F));
        root.addOrReplaceChild("lod4b", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -7F, 4, 1, 1), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild("lod4c", CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -7F, 4, 1, 1), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild("wingb1", CubeListBuilder.create().texOffs(0, 22).addBox(1F, 0F, -1F, 20, 0, 5), PartPose.offsetAndRotation(0F, 11.5F, 0F, -0.1047198F, 0F, 0F));
        root.addOrReplaceChild("wingb2", CubeListBuilder.create().texOffs(0, 22).addBox(1F, 0F, -1F, 20, 0, 5), PartPose.offsetAndRotation(0F, 11.5F, 0F, -0.1047198F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    public void renderToBuffer(com.mojang.blaze3d.vertex.PoseStack pose, com.mojang.blaze3d.vertex.VertexConsumer buf, int light, int overlay, float r, float g, float b, float a) {
        body.render(pose, buf, light, overlay, r, g, b, a);
        head.render(pose, buf, light, overlay, r, g, b, a);
        ear1.render(pose, buf, light, overlay, r, g, b, a);
        ear2.render(pose, buf, light, overlay, r, g, b, a);
        wing1.render(pose, buf, light, overlay, r, g, b, a);
        wing2.render(pose, buf, light, overlay, r, g, b, a);
        tail1.render(pose, buf, light, overlay, r, g, b, a);
        tail2.render(pose, buf, light, overlay, r, g, b, a);
        core1.render(pose, buf, light, overlay, r, g, b, a);
        core2.render(pose, buf, light, overlay, r, g, b, a);
        sphere.render(pose, buf, light, overlay, r, g, b, a);
        sphere2.render(pose, buf, light, overlay, r, g, b, a);
        arm1.render(pose, buf, light, overlay, r, g, b, a);
        arm2.render(pose, buf, light, overlay, r, g, b, a);
        arm3.render(pose, buf, light, overlay, r, g, b, a);
        blade1.render(pose, buf, light, overlay, r, g, b, a);
        blade2.render(pose, buf, light, overlay, r, g, b, a);
        blade3.render(pose, buf, light, overlay, r, g, b, a);
        blade21.render(pose, buf, light, overlay, r, g, b, a);
        blade22.render(pose, buf, light, overlay, r, g, b, a);
        blade23.render(pose, buf, light, overlay, r, g, b, a);
        side1.render(pose, buf, light, overlay, r, g, b, a);
        side2.render(pose, buf, light, overlay, r, g, b, a);
        side3.render(pose, buf, light, overlay, r, g, b, a);
        side4.render(pose, buf, light, overlay, r, g, b, a);
        inner1.render(pose, buf, light, overlay, r, g, b, a);
        inner2.render(pose, buf, light, overlay, r, g, b, a);
        barB1.render(pose, buf, light, overlay, r, g, b, a);
        barB2.render(pose, buf, light, overlay, r, g, b, a);
        barB3.render(pose, buf, light, overlay, r, g, b, a);
        barB4.render(pose, buf, light, overlay, r, g, b, a);
        barB5.render(pose, buf, light, overlay, r, g, b, a);
        barB6.render(pose, buf, light, overlay, r, g, b, a);
        barF1.render(pose, buf, light, overlay, r, g, b, a);
        barF2.render(pose, buf, light, overlay, r, g, b, a);
        barF3.render(pose, buf, light, overlay, r, g, b, a);
        barF4.render(pose, buf, light, overlay, r, g, b, a);
        barF5.render(pose, buf, light, overlay, r, g, b, a);
        barF6.render(pose, buf, light, overlay, r, g, b, a);
        barR1.render(pose, buf, light, overlay, r, g, b, a);
        barR2.render(pose, buf, light, overlay, r, g, b, a);
        barR3.render(pose, buf, light, overlay, r, g, b, a);
        barR4.render(pose, buf, light, overlay, r, g, b, a);
        barL1.render(pose, buf, light, overlay, r, g, b, a);
        barL2.render(pose, buf, light, overlay, r, g, b, a);
        barL3.render(pose, buf, light, overlay, r, g, b, a);
        barL4.render(pose, buf, light, overlay, r, g, b, a);
        head1.render(pose, buf, light, overlay, r, g, b, a);
        head2.render(pose, buf, light, overlay, r, g, b, a);
        head3.render(pose, buf, light, overlay, r, g, b, a);
        head4.render(pose, buf, light, overlay, r, g, b, a);
        cover1.render(pose, buf, light, overlay, r, g, b, a);
        head6.render(pose, buf, light, overlay, r, g, b, a);
        head7.render(pose, buf, light, overlay, r, g, b, a);
        head8.render(pose, buf, light, overlay, r, g, b, a);
        head9.render(pose, buf, light, overlay, r, g, b, a);
        cover2.render(pose, buf, light, overlay, r, g, b, a);
        glow1.render(pose, buf, light, overlay, r, g, b, a);
        glow2.render(pose, buf, light, overlay, r, g, b, a);
        top.render(pose, buf, light, overlay, r, g, b, a);
        lod1a.render(pose, buf, light, overlay, r, g, b, a);
        lod1b.render(pose, buf, light, overlay, r, g, b, a);
        lod1c.render(pose, buf, light, overlay, r, g, b, a);
        lod2a.render(pose, buf, light, overlay, r, g, b, a);
        lod2b.render(pose, buf, light, overlay, r, g, b, a);
        lod2c.render(pose, buf, light, overlay, r, g, b, a);
        lod3a.render(pose, buf, light, overlay, r, g, b, a);
        lod3b.render(pose, buf, light, overlay, r, g, b, a);
        lod3c.render(pose, buf, light, overlay, r, g, b, a);
        lod4a.render(pose, buf, light, overlay, r, g, b, a);
        lod4b.render(pose, buf, light, overlay, r, g, b, a);
        lod4c.render(pose, buf, light, overlay, r, g, b, a);
        wingb1.render(pose, buf, light, overlay, r, g, b, a);
        wingb2.render(pose, buf, light, overlay, r, g, b, a);
    }
}