package mods.defeatedcrow.common.registry;

import net.minecraft.world.level.material.Fluid;
import net.minecraftforge.fluids.ForgeFlowingFluid;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * 1.20.1 Fluid registry — FlowingFluid Source/Flowing + FluidType separation.
 * See doc/fluids/migration-guide.md:12
 * WT-B owns all fluids (18種: vegitable_oil, camellia_oil + 16 brewing). Bootstrap owns the DeferredRegister shells.
 */
public class ModFluids {
    public static final DeferredRegister<Fluid> FLUIDS = DeferredRegister.create(ForgeRegistries.FLUIDS, "defeatedcrow");

    // --- WT-B: OILS (vegitable_oil, camellia_oil) ---
    // public static final RegistryObject<ForgeFlowingFluid> VEG_OIL_SOURCE = FLUIDS.register("vegitable_oil",
    //     () -> new ForgeFlowingFluid.Source(vegProps(ModFluidTypes.VEG_TYPE, ModItems.BUCKET_VEGI_OIL, ModBlocks.BLOCK_VEGI_OIL)));
    // public static final RegistryObject<ForgeFlowingFluid> VEG_OIL_FLOWING = FLUIDS.register("vegitable_oil_flowing",
    //     () -> new ForgeFlowingFluid.Flowing(vegProps(...)));

    // --- WT-B: BREWING 16 (shothu_young/whiskey_young/brandy_young/rum_young/vodka_young + aged + sake_young/beer_young/wine_young + aged) ---
    // All 16 share the same pattern: FluidType (ModFluidTypes) + Source + Flowing

    // Helper will be generated by WT-B:
    // private static ForgeFlowingFluid.Properties vegProps(...){ return new ForgeFlowingFluid.Properties(...).block(...).bucket(...).slopeFindDistance(2).levelDecreasePerBlock(1); }

    private ModFluids() {}
}
